### ISSUE TITLE
Incompat with 1.19.3

### ISSUE THREAD

**Issue by Cape-City** [Steveplays28/pathunderfencegates#10]
Hi,

i get this error, when using the latest release for 1.19.3

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Path Under Fence Gates' (pathunderfencegates) 1.4.0+mc1.19.x with any version that is compatible with:
		 - minecraft 1.19.3
Unmet dependency listing:
	 - Mod 'Path Under Fence Gates' (pathunderfencegates) 1.4.0+mc1.19.x requires any 1.20.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
	 - Mod 'Statement Vanilla Compatibility Module' (statement_vanilla_compatibility) 1.0.1+1.14.4-1.15.2 requires any version between 1.14.0-0 (inclusive) and 1.16.0-0 (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Steveplays28** [comment]
Hi Cape-City, thanks for the report.
Seems like I accidentally changed the compatibility info in the `fabric.mod.json` file in `main` at some point. I'm going to publish a fixed release.

**Comment by Steveplays28** [comment]
Just published a fixed release, [it's up for download](https://github.com/Steveplays28/pathunderfencegates#download).
