### ISSUE TITLE
Crash with MiniTweaks

### ISSUE THREAD

**Issue by SplendidAlakey** [Steveplays28/pathunderfencegates#4]
**MC** 1.19.2
**[MiniTweaks](https://modrinth.com/mod/minitweaks)** 1.3.2
**Path under fence gates** 1.2.1

The game crashes on startup with both mods installed.

Also reported to MiniTweaks.

Logs: https://gist.github.com/SplendidAlakey/0b9531408c5616ac5194b8c7fcfc0e51

**Comment by Steveplays28** [comment]
Hi,

It seems to have to do with the mod's snow shaving carpet rule.
I suppose it crashes because we modify the same class using a mixin, but I use an overwrite instead of an inject.

I'll see if I can fix this issue, thanks for the report.

**Comment by Steveplays28** [comment]
Fixed in [1.2.2](https://github.com/Steveplays28/pathunderfencegates/releases/tag/1.2.2). Sorry for the wait!
